name = "QuadraticProgramSolvers"
uuid = "8d0897ce-7f08-4f75-be29-ad380caf92af"
authors = ["John Zhang <johnzhang@cmu.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
