name = "QuadraticProgramSolvers"
uuid = "8d0897ce-7f08-4f75-be29-ad380caf92af"
authors = ["John Zhang <johnzhang@cmu.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
